modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = "https://github.com/Octol1ttle/DamageVignette/issues"
license = "MIT"

[[mods]]
modId = "damagevignette"
version = "${version}"
displayName = "DamageVignette"
authors = "Octol1ttle"
description = '''
Adds an overlay (similar to getting close to world border) when low on health.
'''
logoFile = "icon.png"

[[dependencies.damagevignette]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.damagevignette]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.2,1.21)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.damagevignette]]
modId = "architectury"
mandatory = true
versionRange = "[9.1.12,)"
ordering = "AFTER"
side = "CLIENT"